### ISSUE TITLE
required html path argument

### ISSUE THREAD

**Issue by landsman** [ragingwind/google-font-importer#2]
Hi,

why is html argument required?
I want use this in my project, based on sass, twig.

Most comfortable solution for me is:
1. define fonts to download in one file
2. download all fonts to defined folder
3. generate css file which defined name (or some default)
4. link that css file to my sass build

:)

Thanks

**Comment by ragingwind** [comment]
it's fit to my build workflow. but It would be fine if you make a new PR for this that make this to support optional html.
